apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: deemp/consumer:latest
          ports:
            - containerPort: 8085
          env:
          - name: "MQ_HOST"
            value: rabbitmq-service
          - name: "MQ_PORT"
            value: "5672"
          - name: "POSTGRES_DB"
            value: "pg_db"
          - name: "MQ_QUEUE"
            value: "hello"
          - name: "DB_HOST"
            value: postgres-service
          - name: "DB_PORT"
            value: "5432"
          - name: "POSTGRES_TABLE"
            value: init_table
          - name: "POSTGRES_USER"
            value: my_admin
          - name: "POSTGRES_PASSWORD"
            value: my_admin