# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: dHZsYWItdXNlcg==
  password: dHZsYWItcGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=