---
# Deployment of `app_msg_producer`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: deemp/producer:latest
          ports:
            - containerPort: 8080
          env:
            - name: "MQ_HOST"
              value: rabbitmq-service
            - name: "MQ_PORT"
              value: "5672"
            - name: "MQ_PASS"
              value: guest
            - name: "MQ_USER"
              value: "guest"
            - name: "MQ_QUEUE"
              value: "hello"
---
# Deployment of `app_msg_consumer`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: deemp/consumer:latest
          ports:
            - containerPort: 8085
          env:
          - name: ""
            value: rabbitmq-service
          - name: "spring.rabbitmq.port"
            value: "5672"
          - name: "spring.rabbitmq.password"
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: password
          - name: "spring.rabbitmq.username"
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: username
          - name: "spring.datasource.url"
            value: "jdbc:postgresql://postgres-service:5432/tvlabdb"
          - name: "spring.datasource.username"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: "spring.datasource.password"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
